In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesRegressor
import matplotlib.pyplot as plt

import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout  
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.

In [15]:
train = pd.read_csv('datasets/podzielone/ml/wszystkie/train_ml.csv', index_col=0)
val1 = pd.read_csv('datasets/podzielone/ml/wszystkie/valid1_ml.csv', index_col=0)
val2 = pd.read_csv('datasets/podzielone/ml/wszystkie/valid2_ml.csv', index_col=0)
val3 = pd.read_csv('datasets/podzielone/ml/wszystkie/valid3_ml.csv', index_col=0)
test = pd.read_csv('datasets/podzielone/ml/wszystkie/test_ml.csv', index_col=0)



train.index = pd.to_datetime(train.index)
val1.index = pd.to_datetime(val1.index)
val2.index = pd.to_datetime(val2.index)
val3.index = pd.to_datetime(val3.index)
test.index = pd.to_datetime(test.index)


train["day_of_week"] = train.index.dayofweek
train["day_of_year"] = train.index.dayofweek
train["week"] = train.index.week
train["quarter"] = train.index.quarter
train["return_ratio"] = train.y_return_ratio.shift()

val1["day_of_week"] = val1.index.dayofweek
val1["day_of_year"] = val1.index.dayofweek
val1["week"] = val1.index.week
val1["quarter"] = val1.index.quarter
val1["return_ratio"] = val1.y_return_ratio.shift()

val2["day_of_week"] = val2.index.dayofweek
val2["day_of_year"] = val2.index.dayofweek
val2["week"] = val2.index.week
val2["quarter"] = val2.index.quarter
val2["return_ratio"] = val2.y_return_ratio.shift()

val3["day_of_week"] = val3.index.dayofweek
val3["day_of_year"] = val3.index.dayofweek
val3["week"] = val3.index.week
val3["quarter"] = val3.index.quarter
val3["return_ratio"] = val3.y_return_ratio.shift()

test["day_of_week"] = test.index.dayofweek
test["day_of_year"] = test.index.dayofweek
test["week"] = test.index.week
test["quarter"] = test.index.quarter
test["return_ratio"] = test.y_return_ratio.shift()


train.columns=train.columns.str.replace('(','')
train.columns=train.columns.str.replace(']','')

val1.columns=val1.columns.str.replace('(','')
val1.columns=val1.columns.str.replace(']','')
val2.columns=val2.columns.str.replace('(','')
val2.columns=val2.columns.str.replace(']','')
val3.columns=val3.columns.str.replace('(','')
val3.columns=val3.columns.str.replace(']','')

val.columns=val.columns.str.replace('(','')
val.columns=val.columns.str.replace(']','')


train1 = train.asfreq('B', method='bfill').fillna(method='bfill')
train2 = pd.concat([train, val1]).asfreq('B', method='bfill').fillna(method='bfill')
train3 = pd.concat([train, val1, val2]).asfreq('B', method='bfill').fillna(method='bfill')

val1 = val1.asfreq('B', method='bfill').fillna(method='bfill')
val2 = val2.asfreq('B', method='bfill').fillna(method='bfill')
val3 = val3.asfreq('B', method='bfill').fillna(method='bfill')
test = test.asfreq('B', method='bfill').fillna(method='bfill')

whole = pd.concat([train, val1, val2, val3, test]).asfreq('B', method='bfill').fillna(method='bfill')
val = pd.concat([val1, val2, val3]).asfreq('B', method='bfill').fillna(method='bfill')


display(train.head(3))
display(val1.head(3))
display(val2.head(3))
display(val3.head(3))
display(test.head(3))
display(whole.head(3))

/home/michal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:70: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,y_return_ratio,ATR,MOM,CCI,EMA,RSI,Will_R,MFI,DX,PLUS_DM,...,ATAN_diff_1,CEIL_diff_1,FLOOR_diff_1,LN_diff_1,LOG10_diff_1,SQRT_diff_1,day_of_week,day_of_year,week,quarter
2012-07-02,-0.026773,0.475985,1.53,148.118434,12.781515,62.987843,-1.546392,59.313104,31.365741,2.350220,...,0.003153,0.0,0.0,0.042874,0.018620,0.078845,0,0,27,3
2012-07-03,0.026022,0.481986,1.05,103.024634,12.824644,57.664648,-22.613065,52.602204,23.907183,2.182347,...,-0.001980,0.0,0.0,-0.027138,-0.011786,-0.050102,1,1,27,3
2012-07-05,-0.010145,0.475416,0.56,110.859729,12.887570,61.020501,-5.025126,57.027455,23.907183,2.026465,...,0.001876,0.0,0.0,0.025689,0.011157,0.047411,3,3,27,3

,y_return_ratio,ATR,MOM,CCI,EMA,RSI,Will_R,MFI,DX,PLUS_DM,...,ATAN_diff_1,CEIL_diff_1,FLOOR_diff_1,LN_diff_1,LOG10_diff_1,SQRT_diff_1,day_of_week,day_of_year,week,quarter
2018-01-02,0.030233,5.125354,7.029999,27.231458,196.912948,45.133485,-42.095010,55.894280,23.134279,13.144963,...,-0.000102,-4.0,-4.0,-0.019955,-0.008666,-0.139483,1,1,1,1
2018-01-03,0.065814,5.187829,7.790008,77.718696,197.070178,53.249819,-4.033801,55.819341,19.229973,13.246030,...,0.000152,6.0,6.0,0.029785,0.012935,0.208708,2,2,1,1
2018-01-04,0.005271,5.842269,14.570007,279.927608,198.063715,65.556102,-4.226792,67.077304,18.683056,26.499882,...,0.000310,13.0,13.0,0.063739,0.027681,0.457215,3,3,1,1

,y_return_ratio,ATR,MOM,CCI,EMA,RSI,Will_R,MFI,DX,PLUS_DM,...,ATAN_diff_1,CEIL_diff_1,FLOOR_diff_1,LN_diff_1,LOG10_diff_1,SQRT_diff_1,day_of_week,day_of_year,week,quarter
2018-03-01,-0.040455,8.425720,9.369995,37.127358,234.729083,54.963241,-28.932093,70.942953,2.299899,24.419310,...,-0.000068,-5.0,-4.0,-0.016638,-0.007226,-0.129951,3,3,9,1
2018-03-02,0.018647,8.964597,-9.209991,-67.945451,234.566562,47.416343,-57.358478,71.264678,24.198760,22.675074,...,-0.000174,-9.0,-10.0,-0.041296,-0.017934,-0.317911,4,4,9,1
2018-03-05,-0.003763,9.392126,-9.960007,-108.267191,234.693880,50.644262,-51.228455,60.063802,31.886239,21.055426,...,0.000079,4.0,4.0,0.018475,0.008024,0.141418,0,0,10,1

,y_return_ratio,ATR,MOM,CCI,EMA,RSI,Will_R,MFI,DX,PLUS_DM,...,ATAN_diff_1,CEIL_diff_1,FLOOR_diff_1,LN_diff_1,LOG10_diff_1,SQRT_diff_1,day_of_week,day_of_year,week,quarter
2018-05-01,0.009960,8.606211,-6.590011,-36.196616,229.129258,46.714722,-49.568247,52.298305,16.163336,22.665165,...,-0.000028,-2.0,-2.0,-0.006338,-0.002753,-0.047602,1,1,18,2
2018-05-02,-0.003654,8.352196,-10.399994,-41.609464,229.000918,48.681141,-41.830750,46.410723,19.251258,21.046224,...,0.000044,3.0,3.0,0.009911,0.004304,0.074498,2,2,18,2
2018-05-03,0.029517,8.009182,-10.059997,-16.440286,228.827311,47.974668,-44.697766,43.162233,15.551078,21.092926,...,-0.000016,-1.0,-1.0,-0.003661,-0.001590,-0.027561,3,3,18,2

,y_return_ratio,ATR,MOM,CCI,EMA,RSI,Will_R,MFI,DX,PLUS_DM,...,ATAN_diff_1,CEIL_diff_1,FLOOR_diff_1,LN_diff_1,LOG10_diff_1,SQRT_diff_1,day_of_week,day_of_year,week,quarter
2018-07-02,0.022541,6.899792,-28.360016,-97.965938,250.580128,36.289331,-94.472074,39.345807,40.019379,13.617902,...,-0.000069,-4.0,-4.0,-0.016578,-0.007200,-0.128109,0,0,27,3
2018-07-03,-0.022292,7.059093,-22.849991,-81.994860,250.042056,42.388575,-75.013896,39.426792,44.725629,12.645195,...,0.000093,6.0,6.0,0.022291,0.009681,0.172505,1,1,27,3
2018-07-04,0.024869,7.082015,-23.330017,-71.397983,249.190310,38.386549,-90.038956,34.350825,39.822012,13.231972,...,-0.000094,-6.0,-6.0,-0.022544,-0.009791,-0.174455,3,3,27,3

,AD,ADD,ADD_diff_1,ADOSC,ADX,ADXR,AD_diff_1,AMD,AMD_,AMD__scaled,...,return_ratio_shift_6,return_ratio_shift_7,roa,roe,roi,rolling variance,super_gry,volume,week,y_return_ratio
2012-07-02,-1.041267e+08,27.39,1.16,7.065183e+06,18.394403,19.959226,1.242960e+07,5.660,82.800000,0.522222,...,-0.045353,0.015861,1.0588,1.4096,1.4028,0.032924,0.0,15412700.0,27,-0.026773
2012-07-03,-1.129559e+08,27.24,-0.15,5.913462e+06,18.788173,19.435457,-8.829132e+06,5.750,83.064516,0.529570,...,0.012461,-0.045353,1.0588,1.4096,1.4028,0.035186,0.0,14542100.0,27,0.026022
2012-07-04,-1.083172e+08,27.27,0.03,6.380666e+06,19.153816,19.121945,4.638700e+06,5.905,83.129032,0.531362,...,-0.031538,0.012461,1.0588,1.4096,1.4028,0.029409,1.0,5482100.0,27,-0.010145

In [4]:
variables = train.columns.tolist()
variables.remove("y_return_ratio")
features = train[variables].columns
target = 'y_return_ratio'

In [8]:
scaler = MinMaxScaler(feature_range=(0, 1))
scalerT = MinMaxScaler(feature_range=(0, 1))

labels = scalerT.fit_transform(pd.DataFrame(train1[target]))
features_set = scaler.fit_transform(train1[variables])
features_set = np.reshape(features_set, (features_set.shape[0], features_set.shape[1], 1))

test_features_set = scaler.fit_transform(val[variables])
test_features_set = np.reshape(test_features_set, (test_features_set.shape[0], test_features_set.shape[1], 1))

model = Sequential()

model.add(LSTM(units=50, return_sequences=True, input_shape=(features_set.shape[1], 1)))
model.add(Dropout(0.2))

model.add(LSTM(units=50, return_sequences=True))  
model.add(Dropout(0.2))

model.add(LSTM(units=50, return_sequences=True))  
model.add(Dropout(0.2))

model.add(LSTM(units=50))  
model.add(Dropout(0.2))

model.add(Dense(units = 1))

model.compile(optimizer = 'adam', loss = 'mean_squared_error')
model.fit(features_set, labels, epochs = 100, batch_size = 32)

predictions = model.predict(test_features_set)
predictions = scalerT.inverse_transform(predictions)

plt.figure(figsize=(10,6))
pd.Series([x[0] for x in predictions], index=y_test1.index).plot(label='pred')
y_test1.plot(label="real")
plt.legend()
plt.show()

WARNING:tensorflow:From /home/michal/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

/home/michal/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
/home/michal/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

WARNING:tensorflow:From /home/michal/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/michal/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
1435/1435 [==============================] - 25s 17ms/step - loss: 0.0086
Epoch 2/100
1435/1435 [==============================] - 24s 17ms/step - loss: 0.0036
Epoch 3/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0035
Epoch 4/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0037
Epoch 5/100
1435/1435 [==============================] - 25s 17ms/step - loss: 0.0037
Epoch 6/100
1435/1435 [==============================] - 22s 16ms/step - loss: 0.0035
Epoch 7/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0036
Epoch 8/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0034
Epoch 9/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0036
Epoch 10/100
1435/1435 [==============================] - 22s 16ms/step - loss: 0.0035
Epoch 11/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0035
Epoch 12/100
1435/1435 [==============================] - 24s 17ms/step - loss: 0.0034
Epoch 13/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0034
Epoch 14/100
1435/1435 [==============================] - 24s 16ms/step - loss: 0.0034
Epoch 15/100
1435/1435 [==============================] - 24s 16ms/step - loss: 0.0034
Epoch 16/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0033
Epoch 17/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0035
Epoch 18/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0034
Epoch 19/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0033
Epoch 20/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0034
Epoch 21/100
1435/1435 [==============================] - 24s 16ms/step - loss: 0.0034
Epoch 22/100
1435/1435 [==============================] - 24s 17ms/step - loss: 0.0034
Epoch 23/100
1435/1435 [==============================] - 24s 17ms/step - loss: 0.0033
Epoch 24/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0034
Epoch 25/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 26/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 27/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0034
Epoch 28/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0034
Epoch 29/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 30/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 31/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 32/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 33/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0033
Epoch 34/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 35/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 36/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 37/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 38/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 39/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0034
Epoch 40/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 41/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0033
Epoch 42/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 43/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 44/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 45/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 46/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 47/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 48/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 49/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0033
Epoch 50/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 51/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 52/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 53/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 54/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 55/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0032
Epoch 56/100
1435/1435 [==============================] - 23s 16ms/step - loss: 0.0032
Epoch 57/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 58/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 59/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 60/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 61/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 62/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 63/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 64/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 65/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 66/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 67/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 68/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 69/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 70/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 71/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 72/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 73/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 74/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 75/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 76/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 77/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 78/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 79/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 80/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 81/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 82/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0031
Epoch 83/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 84/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0031
Epoch 85/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 86/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 87/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 88/100

1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 89/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 90/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0031
Epoch 91/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 92/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 93/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 94/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0031
Epoch 95/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0031
Epoch 96/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 97/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 98/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 99/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0032
Epoch 100/100
1435/1435 [==============================] - 22s 15ms/step - loss: 0.0031

NameError: name 'y_test1' is not defined

In [16]:
corr_matrix = whole.drop(columns=['y_return_ratio']).corr("spearman").abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

var1 = [col for col in upper.columns if upper[col].max() < 0.9]
var2 = [col for col in upper.columns if upper[col].max() < 0.7]
var3 = [col for col in upper.columns if upper[col].max() < 0.5]
var4 = [col for col in upper.columns if upper[col].max() < 0.4]
var5 = [col for col in upper.columns if upper[col].max() < 0.3]

print(len(var1))
print(len(var2))
print(len(var3))
print(len(var4))
print(len(var5))

X_train1 = train1[var1]
y_train1 = train1[target]
X_test1 = val[var1]
y_test1 = val[target]
pd.Series([x[0] for x in predictions], index=y_test1.index).plot(label='pred')

199
142
106
88
65

KeyError: "['NVIDIA_news_publikacja_(6, 100]', 'NVIDIA_news_inni_o_nich_pisza_(1, 3]', 'NVIDIA_news_inni_o_nich_pisza_(0, 1]', 'NVIDIA_news_publikacja_(3, 6]', 'NVIDIA_news_publikacja_(1, 3]', 'ogloszenie_nowej_karty_(0, 1]', 'NVIDIA_news_publikacja_(0, 1]'] not in index"